export const GET_PRODUCTS = "GET_PRODUCTS"
export const LOADING_ACTION = "LOADING_ACTION"
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID"
export const GET_FILTER_PRODUCTS = "GET_FILTER_PRODUCTS"
export const GET_FILTER_QUANTITIES = "GET_FILTER_QUANTITIES"
export const GET_FILTER_TYPES = "GET_FILTER_TYPES"
export const GET_FILTER_STATES = "GET_FILTER_STATES"
export const GET_FILTER_GRAPES = "GET_FILTER_GRAPES"
export const CLEAN_FILTERS = 'CLEAN_FILTERS'

