export const GET_PRODUCTS = "GET_PRODUCTS"
export const LOADING_ACTION = "LOADING_ACTION"
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID"
export const GET_FILTERS = "GET_FILTERS"
export const GET_GREPES = 'GET_GREPES'
export const GET_FILTERED_PRODUCTS = "GET_FILTERED_PRODUCTS"